apiVersion: apps/v1
kind: Deployment
metaData:
  name: rss-site
  namespace: test
  labels:
    owner: ---
    app: web
spec:
  replicas: 1
  selector:
    matchLabels
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: front-end
          image: nginx:latest
          resources:
            requests:
              memory: "640Mi"
